name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup pnpm 10
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      - name: Setup Node 22 with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile && echo install dependencies ok ✅

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # When you enable task distribution, run the e2e-ci task instead of e2e

      - name: Typecheck all projects
        run: |
          pnpm exec nx run components:typecheck && echo typecheck components ok ✅
          pnpm exec nx run config-sync:typecheck && echo typecheck config-sync ok ✅
          pnpm exec nx run image-compare:typecheck && echo typecheck image-compare ok ✅
          pnpm exec nx run jozzo:typecheck && echo typecheck jozzo ok ✅
          pnpm exec nx run recipes:typecheck && echo typecheck recipes ok ✅
          pnpm exec nx run regex-converter:typecheck && echo typecheck regex-converter ok ✅
          pnpm exec nx run sample-web-app-e2e:typecheck && echo typecheck sample-web-app-e2e ok ✅
          pnpm exec nx run sample-web-app:typecheck && echo typecheck sample-web-app ok ✅
          pnpm exec nx run stuff-finder:typecheck && echo typecheck stuff-finder ok ✅
          pnpm exec nx run user-scripts:typecheck && echo typecheck user-scripts ok ✅
          pnpm exec nx run utils:typecheck && echo typecheck utils ok ✅
          pnpm exec nx run vet-web:typecheck && echo typecheck vet-web ok ✅
          pnpm exec nx run vite-plugins:typecheck && echo typecheck vite-plugins ok ✅
          echo typecheck all projects ok ✅

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps && echo playwright install ok ✅

      - name: Run CI Checks
        run: pnpm check:ci && echo run ci checks ok ✅
